model_family: llama2-7b
model_path: /root/autodl-tmp/transformers/llama2-7b-chat-hf
LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

lr: 1e-4 #5e-4  lr should be bigger on Niddle
split: wikipedia
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 10
forget_loss: npo_KL  # type: grad_ascent, grad_diff, dpo, npo, dpo_grad_diff, npo_grad_diff, kto
Niddle_used: False
loss_threshold: -100

npo_coeff: 1.0
grad_diff_coeff: 1.0
KL_coeff: 1.0
ref_policy: fine_tuned
beta: 0.1
weight_decay: 0.01
oracle_outputs_cache_path: /root/autodl-tmp/datasets/oracle_outputs_cache_loss_.pt

seed: 1001
run_index: 1
overwrite_dir: True
eval_steps: 1000000000
warmup_steps: steps_per_epoch

save_dir: ${model_path}/1GPU_${forget_loss}_${lr}_${split}_epoch${num_epochs}_batch${batch_size}_accum${gradient_accumulation_steps}_beta${beta}_ref${ref_policy}_eval${eval_steps}_seed${seed}_${run_index}

eval:
  retain_result: data/${..retain_set}_llama_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  model_path: ${..model_path}
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  aggr_save_dir: ${..aggr_save_dir}
  data_path: [/root/Unlearn_Harry_Potter/Baselines/negative-preference-optimization-main/TOFU/TOFU_data, /root/Unlearn_Harry_Potter/Baselines/negative-preference-optimization-main/TOFU/TOFU_data, /root/Unlearn_Harry_Potter/Baselines/negative-preference-optimization-main/TOFU/TOFU_data, /root/Unlearn_Harry_Potter/Baselines/negative-preference-optimization-main/TOFU/TOFU_data]
  split: ${..split}_perturbed
  split_list:
    - retain_perturbed
    - real_authors_perturbed
    - world_facts_perturbed
    - ${split}

  eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]
  question_key: [question, question, question, question]
  answer_key: [answer, answer, answer, answer]
  base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

  generation:
    max_length: 200
    max_new_tokens: null

  save_generated_text: true

  ds_size: 300

  overwrite: false
  use_pretrained: false

  batch_size: 30